### PR TITLE
Preserve indentation while injecting to layout

### PR DESCRIPTION
**Pull request by welldan97**
This PR is indents injected body to layout according to Point of Insertion. Which is important for proper injecting in indentation based template languages, like Jade. Thanks :)

### CODE REVIEW

**Comment by brunowego** [comment]
+1

**Comment by jacmoe** [comment]
Is this closed and not applied?

I am using the assemble-jade plugin by @welldan97 , however it is not enjoyable due to the way Assemble injects the body..

After applying this fix, Assemble acts nicely when using Jade :smile: 

I had to change a small bit.

Would you be interested in a new PR?

Against master branch, right?

This is actually a show-stopper for me, to be honest..

The code is here:

```
  var injectBody = function(layout, body) {
    //return layout.replace(assemble.engine.bodyRegex, body);
    var indentation = getIndentation(layout);
    var bodyWithIndentation = _.map(body.split('\n'), function (line){
      return line.replace(/^/, indentation);
    }).join('\n');
    return layout.replace(assemble.engine.bodyRegex, bodyWithIndentation);
  };

  var getIndentation = function(layout) {
    var bodyRegex = assemble.engine.bodyRegex;
    var bodyRegexWithIndentation = new RegExp(/\s*/.source + bodyRegex.source);

    return layout.match(bodyRegexWithIndentation)[0]
      .replace(bodyRegex, '');
  };
```

It is a tiny change, but what a difference it makes.

A big :+1: to @welldan97 for writing that plugin!

**Comment by jacmoe** [comment]
I will perform a new PR.

**Comment by jacmoe** [comment]
Took me a while to hunt it down, but here:
https://github.com/assemble/grunt-assemble/pull/30
Not sure if Gulp Assemble has this issue, but I am not using Gulp (yet) :p

**Pull request closed without merging**
