### PR TITLE
Update .verb.md

### PR DESCRIPTION
**Pull request by avr**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks!

**Comment by avr** [comment]
So - there was actually a couple of those.  Sorry I missed the other 2.  Do you actually want another PR for those?  Sorry about that.

**Comment by jonschlinkert** [comment]
that would be great! since we're now starting to transition v0.6.0 I imagine we'll be finding a lot of docs errors, any help is appreciated!

**Comment by avr** [comment]
No problem - here you go: #670

**Comment by jonschlinkert** [comment]
:+1: merged!

**Pull request merged**
