### PR TITLE
replace event-stream's pipe with stream-splice to be more streams2 compliant

### PR DESCRIPTION
**Pull request by dennari**
There are 3 tests that I'm not able to pass. For some reason the `files` array doesn't get populated when inside task. It's probably something to do with `session.bindEmitter`.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks!

> It's probably something to do with session.bindEmitter

that's exactly my guess as well. @doowb did you make some updates to session-cache recently that addresses this?

**Comment by doowb** [comment]
I'll check it out. Thanks for putting this together.

**Comment by doowb** [comment]
Seems like `sessionify` isn't working with `stream-splice`. I'm looking into why. `sessionify` is basically a wrapper around methods on `continuation-local-storage` if anyone else wants to look into it also. I'll create some simplified use cases to make sure it works with different types of stream.

**Comment by jonschlinkert** [comment]
I don't remember closing this - on purpose anyway. feel free to reopen if this is still something we want to do

**Pull request closed without merging**
