### PR TITLE
Update to include assemble-handlebars v0.2.4

### PR DESCRIPTION
**Pull request by spacedawwwg**
would require https://github.com/assemble/assemble-handlebars/pull/22

### CODE REVIEW

**Comment by brunowego** [comment]
+1

**Comment by jonschlinkert** [comment]
@spacedawwwg have you been able to test drive these suggested updates much? if so have you had any issues so far?

**Comment by spacedawwwg** [comment]
@jonschlinkert No issues at this end. I've been using my fork in a recent project and have had no problems at all.

**Comment by jannikegger** [comment]
Hey guys,

is there any update about this issue?
We are using assemble in many projects and it would be great to have handlebars 3.0 :)
So :+1:  for this.

Thanks!

**Comment by doowb** [comment]
@jannikegger try the latest version of `grunt-assemble`. It's using the same code, but has been updated to use handlebars 3.0.

**Comment by jannikegger** [comment]
@doowb Oh nice. I didn't know about that. This is great! Thank you so much :)

**Comment by jonschlinkert** [comment]
safe to say this should be closed here

**Pull request closed without merging**
