### PR TITLE
Update assemblefile.js

### PR DESCRIPTION
**Pull request by avr**
A few tweaks to the assemblefile.js so that it runs as an example.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
the reason `build` isn't used there is that the CLI already handle that. so with your changes if run with `assemble` it will execute twice. could you just remove `build`, then I can merge the changes? thanks

fwiw we've been considering keeping all of the documentation in this repo, since it seems like users prefer to have everything in one place. then we would build `assemble.io` with that assemblefile.js, and the `assemble.io` repo would just have the production files.  thoughts?

**Comment by avr** [comment]
This has been updated.

Maybe I have my environment setup wrong, but the `bin` setting in `package.json` doesn't do anything - so I kept getting `command not found: assemble` when trying to run things.  I just manually ran needed to run `bin/cli.js`.

Also - I think it makes a lot of sense to keep the docs with this repo.  It makes it easy to search and find an answer in code/tests or in docs (especially with the `api` folder you just added).

**Comment by jonschlinkert** [comment]
> Maybe I have my environment setup wrong, but the bin setting in package.json doesn't do anything - so I kept getting command not found: assemble when trying to run things. I just manually ran needed to run bin/cli.js.

did you install assemble globally?

**Comment by avr** [comment]
> did you install assemble globally?

Not for this forked repo - I have it in a dev folder so it's easier work with. Then `npm link` into other projects for testing.  How do you guys usually work on assemble (plus all the other npm packages you manage?)

**Comment by jonschlinkert** [comment]
> How do you guys usually work on assemble (plus all the other npm packages you manage?)

With assemble, before the CLI was hooked up I was doing basically what you had in the pr, then using `node assemblefile` to run it.  assemble doesn't need to be installed locally, so I have it installed globally and just run `assemble`

**Comment by jonschlinkert** [comment]
thanks again!

**Pull request merged**
